from enum import Enum


class OrderEnums(str, Enum):
    MARGIN = "MARGIN"
    MARGIN_LONG_ENTRY = "MARGIN_LONG_ENTRY"
    MARGIN_SHORT_ENTRY = "MARGIN_SHORT_ENTRY"
    MARGIN_LONG_EXIT = "MARGIN_LONG_EXIT"
    MARGIN_SHORT_EXIT = "MARGIN_SHORT_EXIT"
    SPOT = "SPOT"
    SPOT_LONG_ENTRY = "SPOT_LONG_ENTRY"
    SPOT_LONG_EXIT = "SPOT_LONG_EXIT"

    FUTURES = "FUTURES"
    FUTURES_LONG_ENTRY = "FUTURES_LONG_ENTRY"
    FUTURES_SHORT_ENTRY = "FUTURES_SHORT_ENTRY"
    FUTURES_LONG_EXIT = "FUTURES_LONG_EXIT"
    FUTURES_SHORT_EXIT = "FUTURES_SHORT_EXIT"
